"""
Skill Creator Agent — The meta-agent that lets Cipher create new agent skills.

If Cipher doesn't have a skill for something, he can build one.
This is the bootstrapping capability that makes Cipher self-expanding.

The agent generates a new Python file in app/agents/skills/ following the
BaseAgent pattern, then dynamically registers it with the registry.
"""

import ast
import importlib
import importlib.util
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

from app.agents.base import BaseAgent
from app.agents.models import AgentCapability, AgentResult, AgentTask
from app.agents.registry import get_registry
from app.core.logging import logger

SKILLS_DIR = Path(__file__).parent  # app/agents/skills/

# Template for new agent skills
AGENT_TEMPLATE = '''"""
{description}
Auto-generated by Cipher's Skill Creator.
"""

import asyncio
from typing import Any

from app.agents.base import BaseAgent
from app.agents.models import AgentCapability, AgentResult, AgentTask
from app.core.logging import logger


class {class_name}(BaseAgent):
    """{description}"""

    def __init__(self):
        super().__init__(
            name="{agent_name}",
            description="{description}",
            version="1.0.0",
            capabilities=[
{capabilities_block}
            ],
        )

    async def execute(self, task: AgentTask) -> AgentResult:
        """Execute the agent task."""
        logger.info(f"[{{self.name}}] Executing: {{task.instruction[:80]}}")

        try:
{execute_body}

        except Exception as e:
            logger.error(f"[{{self.name}}] Failed: {{e}}")
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=False,
                error=str(e),
            )

    async def verify(self, result: AgentResult) -> bool:
        """Verify execution result."""
        if not result.success:
            return isinstance(result.output, dict) or result.error is not None
        return result.output is not None
'''


class SkillCreatorAgent(BaseAgent):
    """
    Meta-agent: creates new agent skills dynamically.
    When Cipher encounters a task he can't do, he can build the skill.
    """

    def __init__(self):
        super().__init__(
            name="skill_creator_agent",
            description="Create new agent skills dynamically — Cipher builds his own capabilities",
            version="1.0.0",
            capabilities=[
                AgentCapability(
                    name="create_skill",
                    description="Generate and register a new agent skill from a description",
                    category="meta",
                    requires_approval=True,
                    timeout_seconds=120,
                ),
                AgentCapability(
                    name="list_skills",
                    description="List all available agent skills and their capabilities",
                    category="meta",
                    requires_approval=False,
                    timeout_seconds=10,
                ),
                AgentCapability(
                    name="create_script",
                    description="Create a standalone Python script for a one-off task",
                    category="meta",
                    requires_approval=True,
                    timeout_seconds=60,
                ),
            ],
        )

    async def validate(self, task: AgentTask) -> bool:
        """Validate the skill creation task."""
        if not await super().validate(task):
            return False

        action = task.params.get("action", "create_skill")
        if action == "create_skill":
            if "skill_name" not in task.params:
                logger.warning(f"Task {task.task_id}: Missing 'skill_name' parameter")
                return False
            if "description" not in task.params:
                logger.warning(f"Task {task.task_id}: Missing 'description' parameter")
                return False
        return True

    async def execute(self, task: AgentTask) -> AgentResult:
        """Execute a skill creation task."""
        action = task.params.get("action", "create_skill")

        if action == "list_skills":
            return await self._list_skills(task)
        elif action == "create_script":
            return await self._create_script(task)
        else:
            return await self._create_skill(task)

    async def _list_skills(self, task: AgentTask) -> AgentResult:
        """List all registered skills."""
        registry = get_registry()
        agents = registry.list_agents_detailed()
        return AgentResult(
            task_id=task.task_id,
            agent_name=self.name,
            success=True,
            output={
                "agents": agents,
                "total": len(agents),
                "total_capabilities": sum(a["capabilities_count"] for a in agents),
            },
        )

    async def _create_skill(self, task: AgentTask) -> AgentResult:
        """Create a new agent skill."""
        skill_name = task.params["skill_name"]
        description = task.params["description"]
        capabilities = task.params.get("capabilities", [])
        execute_code = task.params.get("execute_code", "")

        # Sanitize skill name
        safe_name = re.sub(r"[^a-z0-9_]", "_", skill_name.lower())
        if not safe_name.endswith("_agent"):
            safe_name += "_agent"

        class_name = "".join(word.capitalize() for word in safe_name.split("_"))
        file_name = f"{safe_name}.py"
        file_path = SKILLS_DIR / file_name

        # Don't overwrite existing skills
        if file_path.exists():
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=False,
                error=f"Skill file already exists: {file_name}. Use a different name.",
            )

        # Build capabilities block
        if capabilities:
            caps_lines = []
            for cap in capabilities:
                caps_lines.append(
                    f'                AgentCapability(\n'
                    f'                    name="{cap.get("name", "default")}",\n'
                    f'                    description="{cap.get("description", "")}",\n'
                    f'                    category="{cap.get("category", "custom")}",\n'
                    f'                    requires_approval={cap.get("requires_approval", False)},\n'
                    f'                    timeout_seconds={cap.get("timeout", 30)},\n'
                    f'                ),'
                )
            capabilities_block = "\n".join(caps_lines)
        else:
            capabilities_block = (
                '                AgentCapability(\n'
                f'                    name="{safe_name.replace("_agent", "")}",\n'
                f'                    description="{description}",\n'
                '                    category="custom",\n'
                '                    requires_approval=False,\n'
                '                    timeout_seconds=30,\n'
                '                ),'
            )

        # Build execute body
        if execute_code:
            execute_body = textwrap.indent(execute_code, "            ")
        else:
            execute_body = textwrap.indent(
                'return AgentResult(\n'
                '    task_id=task.task_id,\n'
                '    agent_name=self.name,\n'
                '    success=True,\n'
                '    output={"message": "Skill executed", "instruction": task.instruction},\n'
                ')',
                "            "
            )

        # Generate the file content
        content = AGENT_TEMPLATE.format(
            description=description,
            class_name=class_name,
            agent_name=safe_name,
            capabilities_block=capabilities_block,
            execute_body=execute_body,
        )

        # Validate syntax before writing
        try:
            ast.parse(content)
        except SyntaxError as e:
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=False,
                error=f"Generated code has syntax error: {e}",
                output={"code": content},
            )

        # Write the file
        file_path.write_text(content)
        logger.info(f"Created new skill file: {file_path}")

        # Try to dynamically load and register the agent
        try:
            spec = importlib.util.spec_from_file_location(
                f"app.agents.skills.{safe_name}", str(file_path)
            )
            module = importlib.util.module_from_spec(spec)
            sys.modules[f"app.agents.skills.{safe_name}"] = module
            spec.loader.exec_module(module)

            # Find the agent class
            agent_class = getattr(module, class_name)
            agent_instance = agent_class()

            # Register it
            registry = get_registry()
            registry.register(agent_instance)

            logger.info(f"Dynamically registered new agent: {safe_name}")

            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=True,
                output={
                    "skill_name": safe_name,
                    "class_name": class_name,
                    "file": str(file_path),
                    "registered": True,
                    "capabilities": len(agent_instance.capabilities),
                },
            )
        except Exception as e:
            logger.warning(f"Skill created but failed to auto-register: {e}")
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=True,
                output={
                    "skill_name": safe_name,
                    "class_name": class_name,
                    "file": str(file_path),
                    "registered": False,
                    "register_error": str(e),
                    "note": "Skill file created. Will be available after server restart.",
                },
            )

    async def _create_script(self, task: AgentTask) -> AgentResult:
        """Create a standalone Python script for a one-off task."""
        script_name = task.params.get("script_name", "cipher_script.py")
        code = task.params.get("code", "")

        if not code:
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=False,
                error="No code provided for script creation",
            )

        # Validate syntax
        try:
            ast.parse(code)
        except SyntaxError as e:
            return AgentResult(
                task_id=task.task_id,
                agent_name=self.name,
                success=False,
                error=f"Script has syntax error: {e}",
            )

        scripts_dir = Path.home() / "Desktop" / "orchid" / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        script_path = scripts_dir / script_name
        script_path.write_text(code)

        return AgentResult(
            task_id=task.task_id,
            agent_name=self.name,
            success=True,
            output={
                "script_path": str(script_path),
                "script_name": script_name,
                "lines": len(code.splitlines()),
            },
        )

    async def verify(self, result: AgentResult) -> bool:
        """Verify skill creation result."""
        if not result.success:
            return result.error is not None

        if not isinstance(result.output, dict):
            return False

        # For skill creation, verify the file exists
        if "file" in result.output:
            return Path(result.output["file"]).exists()

        return True
